### ISSUE TITLE
python2 install problem

### ISSUE THREAD

**Issue by asiazhang** [simon-ritchie/pconst#4]
Hi!in our company some user are still using `python2.7`。After the new release of pconst somedays ago，we encouter a problem:

```shell
[tke-1c6g-14][2024-01-22 11:18:47,117][logger][INFO]: Processing /root/.cache/pip/wheels/f3/75/9c/90f8faac79abafec19a86348e5787775b345ab70bd61e16389/cassdk-1.0.2-py2-none-any.whl
[tke-1c6g-14][2024-01-22 11:18:47,219][logger][INFO]: Processing /root/.cache/pip/wheels/e0/db/95/940791febc2ea4e18fd21ded54c02d6f3e4a95b2d4c06ffd36/rainbow_sdk-1.1.12-py2-none-any.whl
[tke-1c6g-14][2024-01-22 11:18:47,394][logger][INFO]: Processing /root/.cache/pip/wheels/f4/cb/e2/be611f2fc17d536ce8815d1627a938336ea2403a16f4acdbba/injectionkit-1.0.50-py2-none-any.whl
[tke-1c6g-14][2024-01-22 11:18:48,013][logger][INFO]: Collecting pconst
[tke-1c6g-14][2024-01-22 11:18:49,263][logger][INFO]:   Using cached https://****@mirrors.tencent.com/yun/pypi/packages/34/f8/850dc0a3258e8c25eb01b6a3cb995f0bd9ecc1d297f79349ac3ea5e86821/pconst-1.1.1.tar.gz (8.1 kB)
[tke-1c6g-14][2024-01-22 11:18:49,586][logger][INFO]:     ERROR: Command errored out with exit status 1:
[tke-1c6g-14][2024-01-22 11:18:49,586][logger][INFO]:      command: /var/log/cte_agent/cte_repos/TencentCloudTest/COSTest/tarzanzhang_branch/c959391b/cte_env/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-oWc3Tf/pconst/setup.py'"'"'; __file__='"'"'/tmp/pip-install-oWc3Tf/pconst/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-i67VEZ
[tke-1c6g-14][2024-01-22 11:18:49,587][logger][INFO]:          cwd: /tmp/pip-install-oWc3Tf/pconst/
[tke-1c6g-14][2024-01-22 11:18:49,587][logger][INFO]:     Complete output (8 lines):
[tke-1c6g-14][2024-01-22 11:18:49,588][logger][INFO]:     Traceback (most recent call last):
[tke-1c6g-14][2024-01-22 11:18:49,588][logger][INFO]:       File "<string>", line 1, in <module>
[tke-1c6g-14][2024-01-22 11:18:49,588][logger][INFO]:       File "/tmp/pip-install-oWc3Tf/pconst/setup.py", line 4, in <module>
[tke-1c6g-14][2024-01-22 11:18:49,589][logger][INFO]:         from pconst import __version__
[tke-1c6g-14][2024-01-22 11:18:49,589][logger][INFO]:       File "pconst/__init__.py", line 4
[tke-1c6g-14][2024-01-22 11:18:49,590][logger][INFO]:         __version__: str = '1.1.1'
[tke-1c6g-14][2024-01-22 11:18:49,590][logger][INFO]:                    ^
[tke-1c6g-14][2024-01-22 11:18:49,590][logger][INFO]:     SyntaxError: invalid syntax
[tke-1c6g-14][2024-01-22 11:18:49,591][logger][INFO]:     ----------------------------------------
[tke-1c6g-14][2024-01-22 11:18:49,591][logger][INFO]: ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[tke-1c6g-14][2024-01-22 11:18:49,625][logger][ERROR]: install test case library requirements failed.
[tke-1c6g-14][2024-01-22 11:18:52,628][logger][INFO]: start to install test case library requirements.
``` 

Can the pconst new version be strict to >= python3？Maybe it will interrupt some python2 user, thanks.

**Comment by simon-ritchie** [comment]
@asiazhang 

Ah, my apologies. I thought it would be okay to drop support for Python 2, but it seems it's being used.

I'll restore support for Python 2.7!

**Comment by simon-ritchie** [comment]
@asiazhang 

Reverted and probably supported Python 2.7!

Please install v1.1.2 (`$ pip install apysc==1.1.2`)

P.S. If you find this useful, I'd appreciate it if you could leave a star for this repository!
